[package]
name    = "cloudship"
version = "0.0.1"
authors = ["Bjørn Nordbø <bn@strangedays.no>", "Martin Hoffmann <hn@nvnc.de>"]

[dependencies]
bytes		= "0.3"
docopt  	= "0.6"
env_logger	= "0.3"
hyper		= "0.6"
log		= "0.3"
mio		= "0.5"
nickel  	= "0.7"
nom		= "1.0"
tick		= { git = "https://github.com/seanmonstar/tick.git" }
xml-rs  	= "0.2"

[[bin]]
name = "cloudship"
doc  = false
