[package]
name    = "cloudship"
version = "0.1.0"
authors = ["Bjørn Nordbø <bn@strangedays.no>"]

[dependencies]
docopt  = "0.6.*"
hyper   = "0.6.*"

[dependencies.nickel]
git = "https://github.com/nickel-org/nickel.rs.git"
